export const phases = [
  {
    id: 1,
    name: "Phase 1",
    subtitle: "Restore & Protect",
    weeks: "Weeks 1–3",
    color: "#4ECDC4",
    accent: "#2BAE9C",
    goal: "Reduce swelling, restore range of motion, activate the quad and VMO without loading the joint.",
    note: "Focus on quality over intensity. No pain — discomfort is okay, sharp pain is not.",
    exercises: [
      {
        name: "Quad Sets",
        sets: "3 × 15",
        rest: "30s",
        desc: "Sit with leg straight. Tighten quad by pressing knee into floor. Hold 5s. Builds VMO activation without joint load.",
        cue: "Imagine squeezing a towel under your knee.",
      },
      {
        name: "Straight Leg Raises",
        sets: "3 × 12",
        rest: "30s",
        desc: "Lie flat, bend one knee. Raise straight leg to ~45°, hold 2s, lower slowly. No joint stress.",
        cue: "Keep your core braced so your lower back doesn't arch.",
      },
      {
        name: "Heel Slides",
        sets: "3 × 10",
        rest: "30s",
        desc: "Lying down, slowly slide heel toward glute and back. Restores flexion ROM gently.",
        cue: "Slide to the edge of comfortable — not into pain.",
      },
      {
        name: "Ankle Pumps",
        sets: "2 × 20",
        rest: "20s",
        desc: "Pump foot up and down at ankle. Improves circulation and reduces swelling.",
        cue: "Do these throughout the day, not just during sessions.",
      },
      {
        name: "Clamshells",
        sets: "3 × 15 each side",
        rest: "30s",
        desc: "Side-lying with knees bent at 90°. Open top knee like a clamshell. Activates glute med to stabilize the knee.",
        cue: "Don't let your hips roll back — keep your pelvis stacked.",
      },
      {
        name: "Terminal Knee Extension (TKE)",
        sets: "3 × 15",
        rest: "30s",
        desc: "With a band around back of knee, start slightly bent, straighten fully. Critical for VMO and quad control at end range.",
        cue: "Squeeze at full extension. This is the money move for meniscus rehab.",
      },
      {
        name: "Seated Knee Flexion (chair)",
        sets: "3 × 10",
        rest: "30s",
        desc: "Sit at edge of chair, let gravity gently pull heel down to increase bend. Use other foot to assist gently if needed.",
        cue: "Gravity-assisted — don't force it.",
      },
    ],
  },
  {
    id: 2,
    name: "Phase 2",
    subtitle: "Load & Stabilize",
    weeks: "Weeks 4–8",
    color: "#F7B731",
    accent: "#E5A020",
    goal: "Progressive weight-bearing, single-leg stability, introduce functional movement patterns.",
    note: "Begin when: full extension restored, flexion past 120°, minimal swelling, quad firing reliably.",
    exercises: [
      {
        name: "Mini Squats (0–60°)",
        sets: "3 × 15",
        rest: "60s",
        desc: "Squat to only 60° of knee bend. Builds quad strength in a safe range before progressing depth.",
        cue: "Drive knees out over toes. Slow on the way down (3 count).",
      },
      {
        name: "Step-Ups (low box)",
        sets: "3 × 10 each leg",
        rest: "60s",
        desc: '6–8" box. Lead with surgical leg. Controls quad eccentrically going down. Highly functional.',
        cue: "Don't push off the back foot — make the front leg do the work.",
      },
      {
        name: "Lateral Band Walks",
        sets: "3 × 15 steps each way",
        rest: "45s",
        desc: "Band around ankles or just above knees. Walk sideways in half-squat. Builds hip abductors to protect knee.",
        cue: "Keep chest tall and don't let knees cave in.",
      },
      {
        name: "Single-Leg Balance",
        sets: "3 × 30s each leg",
        rest: "30s",
        desc: "Stand on one leg. Progress to eyes closed, then on a balance disc. Trains proprioception — critical post-meniscus surgery.",
        cue: "Slight knee bend. Fight the wobble — that's the training.",
      },
      {
        name: "Romanian Deadlift (RDL)",
        sets: "3 × 10",
        rest: "60s",
        desc: "Hip hinge with light weight. Builds hamstrings and glutes that unload the knee. Start with bodyweight or light dumbbells.",
        cue: "Push hips back, not down. Feel stretch in hamstring.",
      },
      {
        name: "Wall Sit",
        sets: "3 × 20–40s",
        rest: "60s",
        desc: "Isometric quad strengthening. Adjust depth to comfort. Great for building quad endurance.",
        cue: "Thighs parallel to floor if tolerable. Push through heels.",
      },
      {
        name: "Calf Raises (bilateral → single leg)",
        sets: "3 × 15",
        rest: "30s",
        desc: "Builds calf/Achilles complex that absorbs load at the ankle, reducing what transfers to the knee.",
        cue: "Slow and controlled. Full range — all the way up and down.",
      },
      {
        name: "Glute Bridges → Single-Leg",
        sets: "3 × 12",
        rest: "45s",
        desc: "Progress from bilateral to single-leg. Posterior chain activation reduces anterior knee stress.",
        cue: "Drive through the heel. Squeeze glute at the top.",
      },
    ],
  },
  {
    id: 3,
    name: "Phase 3",
    subtitle: "Return to Sport",
    weeks: "Weeks 9–16+",
    color: "#FF6B6B",
    accent: "#E05555",
    goal: "Restore full strength, power, and sport-specific movement. Gradual return to running and athletic activity.",
    note: "Begin when: single-leg squat with good form, no swelling after Phase 2 workouts, cleared by PT/surgeon.",
    exercises: [
      {
        name: "Full Depth Squats",
        sets: "4 × 8",
        rest: "90s",
        desc: "Progress to full depth as tolerated. Add load progressively. Return of strength symmetry (within 90% of other leg) is the goal.",
        cue: "Knees track over toes. No valgus collapse.",
      },
      {
        name: "Bulgarian Split Squat",
        sets: "3 × 8 each leg",
        rest: "90s",
        desc: "Rear foot elevated split squat. Best single-leg strength builder. Targets quad, glute, and hip flexor simultaneously.",
        cue: "Torso upright. Front shin vertical. Go slow — 3s down.",
      },
      {
        name: "Step-Down Eccentrics (high box)",
        sets: "3 × 8 each leg",
        rest: "60s",
        desc: "Stand on box, slowly lower one foot to floor over 5 seconds. The gold standard eccentric for knee rehab.",
        cue: "Control the landing leg. Don't let the knee cave.",
      },
      {
        name: "Lateral Bounds (low impact)",
        sets: "3 × 8 each way",
        rest: "60s",
        desc: "Controlled lateral hop and stick landing. Reintroduces lateral loading and proprioception under dynamic conditions.",
        cue: "Stick each landing for 2s before next rep. Quality > quantity.",
      },
      {
        name: "Farmers Carry",
        sets: "3 × 30m",
        rest: "60s",
        desc: "Heavy carry with good posture. Builds total-body stability, grip, and core. Highly functional for daily life.",
        cue: "Shoulders back, ribs down, brace core. Walk tall.",
      },
      {
        name: "Sled Push / Pull",
        sets: "4 × 20m",
        rest: "90s",
        desc: "Low-impact high-load conditioning. Safer for the knee than running — no impact, pure concentric quad work.",
        cue: "Drive through the ground. Lean into the sled.",
      },
      {
        name: "Run-Walk Protocol",
        sets: "Per program below",
        rest: "Per program",
        desc: "Week 9: Walk 4 min / Run 1 min × 5. Progress run intervals weekly. Target: continuous 20-min run by week 14.",
        cue: "No pain during or 24h after. That's the green light to progress.",
      },
      {
        name: "Box Jumps (landing focus)",
        sets: "3 × 5",
        rest: "90s",
        desc: "Jump onto box, step down (don't jump down). Reintroduces plyometric loading with controlled landing stress.",
        cue: "Land softly, absorb with hips and knees. No stiff landings.",
      },
    ],
  },
];

export const UNLOCK_CRITERIA = {
  0: [
    "Full knee extension restored",
    "Flexion past 120°",
    "Minimal swelling post-exercise",
    "Quad activating reliably (TKE reps feel strong)",
  ],
  1: [
    "Single-leg squat with good control",
    "No swelling after Phase 2 sessions",
    "Cleared by surgeon / PT",
    "Strength within ~90% of other leg",
  ],
};
